# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/third_party/webrtc/modules/out
.PHONY: all
all:
	$(MAKE) -C ../../.. audio_processing_offsets PCM16B webrtc_opus G722 G711 webrtc_i420 bitrate_controller audioproc_debug_proto paced_sender udp_transport remote_bitrate_estimator audio_processing_neon iLBC iSAC audio_device isac_neon CNG rtp_rtcp webrtc_video_coding iSACFix audio_processing NetEq audio_coding_module webrtc_utility media_file video_capture_module video_processing video_render_module audio_conference_mixer
