# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := libsrtp
DEFS_Debug := \
	'-DHAVE_STDLIB_H' \
	'-DHAVE_STRING_H' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCPU_CISC' \
	'-DHAVE_INT16_T' \
	'-DHAVE_INT32_T' \
	'-DHAVE_INT8_T' \
	'-DHAVE_UINT16_T' \
	'-DHAVE_UINT32_T' \
	'-DHAVE_UINT64_T' \
	'-DHAVE_UINT8_T' \
	'-DSIZEOF_UNSIGNED_LONG=4' \
	'-DSIZEOF_UNSIGNED_LONG_LONG=8' \
	'-DHAVE_STDINT_H' \
	'-DHAVE_INTTYPES_H' \
	'-DHAVE_NETINET_IN_H' \
	'-DINLINE=inline' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_GPU=1' \
	'-DUSE_OPENSSL=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_BUILD_ID=""' \
	'-DHAVE_SYS_UIO_H' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-format \
	-mthumb \
	-march=armv7-a \
	-mtune=cortex-a8 \
	-mfloat-abi=softfp \
	-mfpu=vfpv3-d16 \
	-fno-tree-sra \
	-fuse-ld=gold \
	-Wno-psabi \
	-mthumb-interwork \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fstack-protector \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	--sysroot=/home/richard/android-sdk/android-ndk-r8d/platforms/android-9/arch-arm \
	-I/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/stlport/stlport \
	-I/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/gnu-libstdc++/4.6/include \
	-Os \
	-g \
	-fomit-frame-pointer \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated \
	-Wno-abi

INCS_Debug := \
	-Ithird_party/libsrtp/config \
	-Ithird_party/libsrtp/srtp/include \
	-Ithird_party/libsrtp/srtp/crypto/include

DEFS_Release := \
	'-DHAVE_STDLIB_H' \
	'-DHAVE_STRING_H' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCPU_CISC' \
	'-DHAVE_INT16_T' \
	'-DHAVE_INT32_T' \
	'-DHAVE_INT8_T' \
	'-DHAVE_UINT16_T' \
	'-DHAVE_UINT32_T' \
	'-DHAVE_UINT64_T' \
	'-DHAVE_UINT8_T' \
	'-DSIZEOF_UNSIGNED_LONG=4' \
	'-DSIZEOF_UNSIGNED_LONG_LONG=8' \
	'-DHAVE_STDINT_H' \
	'-DHAVE_INTTYPES_H' \
	'-DHAVE_NETINET_IN_H' \
	'-DINLINE=inline' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_GPU=1' \
	'-DUSE_OPENSSL=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_BUILD_ID=""' \
	'-DHAVE_SYS_UIO_H' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-format \
	-mthumb \
	-march=armv7-a \
	-mtune=cortex-a8 \
	-mfloat-abi=softfp \
	-mfpu=vfpv3-d16 \
	-fno-tree-sra \
	-fuse-ld=gold \
	-Wno-psabi \
	-mthumb-interwork \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fstack-protector \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	--sysroot=/home/richard/android-sdk/android-ndk-r8d/platforms/android-9/arch-arm \
	-I/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/stlport/stlport \
	-I/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/gnu-libstdc++/4.6/include \
	-Os \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections \
	-fomit-frame-pointer

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated \
	-Wno-abi

INCS_Release := \
	-Ithird_party/libsrtp/config \
	-Ithird_party/libsrtp/srtp/include \
	-Ithird_party/libsrtp/srtp/crypto/include

OBJS := \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/srtp/ekt.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/srtp/srtp.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/cipher/aes.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/cipher/aes_cbc.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/cipher/aes_icm.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/cipher/cipher.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/cipher/null_cipher.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/hash/auth.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/hash/hmac.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/hash/null_auth.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/hash/sha1.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/kernel/alloc.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/kernel/crypto_kernel.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/kernel/err.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/kernel/key.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/math/datatypes.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/math/gf2_8.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/math/stat.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/replay/rdb.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/replay/rdbx.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/replay/ut_sim.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/rng/ctr_prng.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/rng/prng.o \
	$(obj).target/$(TARGET)/third_party/libsrtp/srtp/crypto/rng/rand_source.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-z,relro \
	-Wl,-z,now \
	-fuse-ld=gold \
	-nostdlib \
	-Wl,--no-undefined \
	-Wl,--exclude-libs=ALL \
	--sysroot=/home/richard/android-sdk/android-ndk-r8d/platforms/android-9/arch-arm \
	-Wl,--icf=safe \
	-L/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/stlport/libs/armeabi-v7a \
	-L/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/gnu-libstdc++/4.6/libs/armeabi-v7a \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-z,relro \
	-Wl,-z,now \
	-fuse-ld=gold \
	-nostdlib \
	-Wl,--no-undefined \
	-Wl,--exclude-libs=ALL \
	--sysroot=/home/richard/android-sdk/android-ndk-r8d/platforms/android-9/arch-arm \
	-Wl,--icf=safe \
	-L/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/stlport/libs/armeabi-v7a \
	-L/home/richard/android-sdk/android-ndk-r8d/sources/cxx-stl/gnu-libstdc++/4.6/libs/armeabi-v7a \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	 \
	-lstlport_static \
	/home/richard/android-sdk/android-ndk-r8d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/libgcc.a \
	-lc \
	-ldl \
	-lstdc++ \
	-lm

$(obj).target/third_party/libsrtp/libsrtp.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/third_party/libsrtp/libsrtp.a: LIBS := $(LIBS)
$(obj).target/third_party/libsrtp/libsrtp.a: TOOLSET := $(TOOLSET)
$(obj).target/third_party/libsrtp/libsrtp.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/third_party/libsrtp/libsrtp.a
# Add target alias
.PHONY: libsrtp
libsrtp: $(obj).target/third_party/libsrtp/libsrtp.a

# Add target alias to "all" target.
.PHONY: all
all: libsrtp

# Add target alias
.PHONY: libsrtp
libsrtp: $(builddir)/libsrtp.a

# Copy this to the static library output path.
$(builddir)/libsrtp.a: TOOLSET := $(TOOLSET)
$(builddir)/libsrtp.a: $(obj).target/third_party/libsrtp/libsrtp.a FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/libsrtp.a
# Short alias for building this static library.
.PHONY: libsrtp.a
libsrtp.a: $(obj).target/third_party/libsrtp/libsrtp.a $(builddir)/libsrtp.a

# Add static library to "all" target.
.PHONY: all
all: $(builddir)/libsrtp.a

