# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/third_party/webrtc/system_wrappers/source/out
.PHONY: all
all:
	$(MAKE) -C ../../../.. cpu_features_android system_wrappers
